//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionGuichetAutomatique
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.Comptes = new HashSet<Compte>();
        }

        public Client(string codeClient, decimal numeroNIP, string nomClient, string prenomClient, string telephone, string courriel, bool statusClient)
        {
            CodeClient = codeClient;
            NumeroNIP = numeroNIP;
            NomClient = nomClient;
            PrenomClient = prenomClient;
            Telephone = telephone;
            Courriel = courriel;
            StatusClient = statusClient;
        }

        public string CodeClient { get; set; }
        public decimal NumeroNIP { get; set; }
        public string NomClient { get; set; }
        public string PrenomClient { get; set; }
        public string Telephone { get; set; }
        public string Courriel { get; set; }
        public bool StatusClient { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Compte> Comptes { get; set; }
    }
}
