//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionGuichetAutomatique
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class guichetAutomatiqueEntities : DbContext
    {
        public guichetAutomatiqueEntities()
            : base("name=guichetAutomatiqueEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Compte> Comptes { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }
        public virtual DbSet<typeCompte> typeComptes { get; set; }
        public virtual DbSet<TypeTransaction> TypeTransactions { get; set; }
    }
}
