//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionGuichetAutomatique
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public Transaction( DateTime? dateTransaction, double? montantTransaction, int? compteSource, int? compteDestination, int? codeTypeTransaction)
        {
           // NumroTransaction = numroTransaction;
            DateTransaction = dateTransaction;
            MontantTransaction = montantTransaction;
            CompteSource = compteSource;
            CompteDestination = compteDestination;
            CodeTypeTransaction = codeTypeTransaction;
        }

        public Transaction() { }

        public int NumroTransaction { get; set; }
        public Nullable<System.DateTime> DateTransaction { get; set; }
        public Nullable<double> MontantTransaction { get; set; }
        public Nullable<int> CompteSource { get; set; }
        public Nullable<int> CompteDestination { get; set; }
        public Nullable<int> CodeTypeTransaction { get; set; }
    
        public virtual Compte Compte { get; set; }
        public virtual Compte Compte1 { get; set; }
        public virtual TypeTransaction TypeTransaction { get; set; }
    }
}
